dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "**/bin/**/*"
  - "**/obj/**/*"
  - ".typo-ci.yml"

# Any typos we should ignore?
excluded_words:
  - typoci
  - Xce
  - Fody

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true