# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      id: setup_msbuild
      uses: ./
      with:
        vs-version: "[16.4,16.6]"
    
    - name: msbuild UndoRedo.sln
