name: Ms Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore nuget packages
      run: msbuild -t:restore
      working-directory: src
    
    - name: Build sources
      run: msbuild UndoRedo.sln
      working-directory: src
