name: Ms Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Restore nuget packages
      run: dotnet restore
    
    - name: Build test app
      run: msbuild Xce.UndoRedo/Xce.UndoRedo.csproj
    
    - name: Build unit tests
      run: msbuild Fody.Test/Xce.TrackingItem.Fody.UnitTests/Xce.TrackingItem.Fody.UnitTests.csproj

    - name: Run unit tests
      run: dotnet test